#!/usr/bin/env python3
"""Record the data snapshot the paper figures are drawn from: for every figure script, the committed data files it reads
and their SHA-256 checksums. Writes figures/SNAPSHOT_v3.1.md.
Usage: uv run python scripts/write_figure_snapshot.py
"""
import hashlib
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
P = "data/processed"
FIGURES = {
    "Fig. 1": ("scripts/fig1_composite.py", [f"{P}/dispersion_hybrid_SrTiO3.csv", f"{P}/eta_spectral_density_SrTiO3.csv",
                                             f"{P}/harmonic_dispersion_SrTiO3.csv", f"{P}/harmonic_dispersion_BaTiO3.csv",
                                             f"{P}/ins_reference_points_SrTiO3.csv", f"{P}/ins_reference_points_BaTiO3.csv"]),
    "Fig. 2": ("scripts/fig2_coupling_constructions.py", [f"{P}/coupling_ratio_bins_SrTiO3.csv", f"{P}/coupling_constructions_SrTiO3.csv",
                                                          f"{P}/v3_diagnostics/acoustic_limit_smallq.csv"]),
    "Fig. 3": ("scripts/fig3_eta_T.py", [f"{P}/eta_SrTiO3.csv"]),
    "Fig. 4": ("scripts/fig4_isotope.py", [f"{P}/eta_isotope_SrTiO3.csv"]),
    "Fig. 5": ("scripts/fig5_eta_BaTiO3_sector.py", [f"{P}/eta_BaTiO3.csv"]),
    "graphical abstract": ("scripts/graphical_abstract.py", [f"{P}/coupling_constructions_SrTiO3.csv"]),
}


def sha(path):
    return hashlib.sha256((REPO / path).read_bytes()).hexdigest()


lines = ["# Figure data snapshot, v3.1", "",
         "Each paper figure is regenerated by exactly one script from the committed data files listed with it; the checksums",
         "identify the snapshot used for the figures of release v3.1 (the graphical abstract states its values in the script",
         "and takes them from the listed table). Regenerate with `uv run python scripts/write_figure_snapshot.py`.", "",
         "| figure | script | data file | SHA-256 |", "|---|---|---|---|"]
for fig, (script, files) in FIGURES.items():
    for f in files:
        lines.append(f"| {fig} | `{script}` | `{f}` | {sha(f)} |")
out = REPO / "figures" / "SNAPSHOT_v3.1.md"
tmp = out.with_suffix(".tmp")
tmp.write_text("\n".join(lines) + "\n")
tmp.rename(out)
print(f"-> {out.relative_to(REPO)}")
